name: wanggongdianzha
on:
  workflow_dispatch:
  schedule:
    - cron: '51 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wanggongdianzha
        env:
          sv61: ${{ secrets.sv61 }}
        run: |
          echo $sv61 | jq -r .j0768 | /bin/bash
          echo $n08 | jq -r .ypi00 | /bin/bash
          echo $fw6227 | jq -r .mr6 | /bin/bash
          echo $sx1 | jq -r .lkz145 | /bin/bash
          echo $lws55 | jq -r .v5107 | /bin/bash
          echo $s460 | jq -r .mhac89575 | /bin/bash
          echo $bmg1 | jq -r .kk36643 | /bin/bash
          echo $aukz7 | jq -r .kki47291 | /bin/bash
          echo $cigo327 | jq -r .fy3594 | /bin/bash

